#ifndef PN3180_DEFS_H
#define PN3180_DEFS_H

// IO ports
// 10  I | RST  | PB0
#define PIN_RESET	(1 << 0)
//  1  I | NSS  | PB4 | SS
#define PIN_NSS		(1 << 4)
//  3  I | MOSI | PB5 | MOSI
#define PIN_MOSI	(1 << 5)
//  5  O | MISO | PB6 | MISO
#define PIN_MISO	(1 << 6)
//  7  I | SCK  | PB7 | SCK
#define PIN_SCK		(1 << 7)
//  8  O | BUSY | PD3 | INT1
#define PIN_BUSY	(1 << 3)
// 38  O | GPIO | PD4
#define PIN_GPIO	(1 << 4)
// 39  O | IRQ  | PD2 | INT0
#define PIN_IRQ		(1 << 2)
// 40  O | AUX  | PD7
#define PIN_AUX1	(1 << 7)
//  2 IO | REQ  | PD5
#define PIN_REQ		(1 << 5)

// Commands
#define CMD_WRITE_REGISTER			0x00
#define CMD_WRITE_REGISTER_OR_MASK		0x01
#define CMD_WRITE_REGISTER_AND_MASK		0x02
#define CMD_WRITE_REGISTER_MULTIPLE		0x03
#define CMD_READ_REGISTER			0x04
#define CMD_READ_REGISTER_MULTIPLE		0x05
#define CMD_WRITE_EEPROM			0x06
#define CMD_READ_EEPROM				0x07
#define CMD_WRITE_TX_DATA			0x08
#define CMD_SEND_DATA				0x09
#define CMD_READ_DATA				0x0A
#define CMD_SWITCH_MODE				0x0B
#define CMD_MIFARE_AUTHENTICATE			0x0C
#define CMD_EPC_INVENTORY			0x0D
#define CMD_EPC_RESUME_INVENTORY		0x0E
#define CMD_EPC_RETRIEVE_INVENTORY_RESULT_SIZE	0x0F
#define CMD_EPC_RETRIEVE_INVENTORY_RESULT	0x10
#define CMD_LOAD_RF_CONFIG			0x11
#define CMD_UPDATE_RF_CONFIG			0x12
#define CMD_RETRIEVE_RF_CONFIG_SIZE		0x13
#define CMD_RETRIEVE_RF_CONFIG			0x14
#define CMD_RF_ON				0x16
#define CMD_RF_OFF				0x17
#define CMD_CONFIGURE_TESTBUS_DIGITAL		0x18
#define CMD_CONFIGURE_TESTBUS_ANALOG		0x19

// Registers
#define REG_SYSTEM_CONFIG		0x00
#define REG_IRQ_ENABLE			0x01
#define REG_IRQ_STATUS			0x02
#define REG_IRQ_CLEAR			0x03
#define REG_TRANSCEIVER_CONFIG		0x04
#define REG_PADCONFIG			0x05
#define REG_PADOUT			0x07
#define REG_TIMER0_STATUS		0x08
#define REG_TIMER1_STATUS		0x09
#define REG_TIMER2_STATUS		0x0A
#define REG_TIMER0_RELOAD		0x0B
#define REG_TIMER1_RELOAD		0x0C
#define REG_TIMER2_RELOAD		0x0D
#define REG_TIMER0_CONFIG		0x0E
#define REG_TIMER1_CONFIG		0x0F
#define REG_TIMER2_CONFIG		0x10
#define REG_RX_WAIT_CONFIG		0x11
#define REG_CRC_RX_CONFIG		0x12
#define REG_RX_STATUS			0x13
#define REG_TX_UNDERSHOOT_CONFIG	0x14
#define REG_TX_OVERSHOOT_CONFIG		0x15
#define REG_TX_DATA_MOD			0x16
#define REG_TX_WAIT_CONFIG		0x17
#define REG_TX_CONFIG			0x18
#define REG_CRC_TX_CONFIG		0x19
#define REG_SIGPRO_CONFIG		0x1A
#define REG_SIGPRO_CM_CONFIG		0x1B
#define REG_SIGPRO_RM_CONFIG		0x1C
#define REG_RF_STATUS			0x1D
#define REG_AGC_CONFIG			0x1E
#define REG_AGC_VALUE			0x1F
#define REG_RF_CONTROL_TX		0x20
#define REG_RF_CONTROL_TX_CLK		0x21
#define REG_RF_CONTROL_RX		0x22
#define REG_LD_CONTROL			0x23
#define REG_SYSTEM_STATUS		0x24
#define REG_TEMP_CONTROL		0x25
#define REG_AGC_REF_CONFIG		0x26
#define REG_DPC_CONFIG			0x27
#define REG_EMD_CONTROL			0x28
#define REG_ANT_CONTROL			0x29
#define REG_TX_CONTROL			0x36
#define REG_SIGPRO_RM_CONFIG_EXTENSION	0x39

// EEPROM
#define EEPROM_DIE_ID				0x00
#define EEPROM_PRODUCT_VERSION			0x10
#define EEPROM_FIRMWARE_VERSION			0x12
#define EEPROM_EEPROM_VERSION			0x14
#define EEPROM_IDLE_IRQ_AFTER_BOOT		0x16
#define EEPROM_TESTBUS_ENABLE			0x17
#define EEPROM_XTAL_BOOT_TIME			0x18
#define EEPROM_IRQ_PIN_CONFIG			0x1A
#define EEPROM_MISO_PULLUP_ENABLE		0x1B
#define EEPROM_PLL_DEFAULT_SETTING		0x1C
#define EEPROM_PLL_DEFAULT_SETTING_ALM		0x24
#define EEPROM_PLL_LOCK_SETTING			0x2c
#define EEPROM_CLOCK_CONFIG			0x30
#define EEPROM_MFC_AUTH_TIMEOUT			0x32
#define EEPROM_LPCD_REFERENCE_VALUE		0x34
#define EEPROM_LPCD_FIELD_ON_TIME		0x36
#define EEPROM_LPCD_THRESHOLD			0x37
#define EEPROM_LPCD_REFVAL_GPO_CONTROL		0x38
#define EEPROM_LPCD_GPO_TOGGLE_BEFORE_FIELD_ON	0x39
#define EEPROM_LPCD_GPO_TOGGLE_AFTER_FIELD_OFF	0x3A
#define EEPROM_NFCLD_SENSITIVITY_VAL		0x3B
#define EEPROM_FIELD_ON_CP_SETTLE_TIME		0x3C
#define EEPROM_RF_DEBOUNCE_TIMEOUT		0x3F
#define EEPROM_SENS_RES				0x40
#define EEPROM_NFCID1				0x42
#define EEPROM_SEL_RES				0x45
#define EEPROM_FELICA_POLLING_RESPONSE		0x46
#define EEPROM_RandomUID_enable			0x51
#define EEPROM_RANDOM_UID_ENABLE		0x58
#define EEPROM_DPC_CONTROL			0x59
#define EEPROM_DPC_TIME				0x5A
#define EEPROM_DPC_XI				0x5C
#define EEPROM_AGC_CONTROL			0x5D
#define EEPROM_DPC_THRSH_HIGH			0x5F
#define EEPROM_DPC_THRSH_LOW			0x7D
#define EEPROM_DPC_DEBUG			0x7F
#define EEPROM_DPC_AGC_SHIFT_VALUE		0x80
#define EEPROM_DPC_AGC_GEAR_LUT_SIZE		0x81
#define EEPROM_DPC_AGC_GEAR_LUT			0x82
#define EEPROM_DPC_GUARD_FAST_MODE		0x91
#define EEPROM_DPC_GUARD_SOF_DETECTED		0x93
#define EEPROM_DPC_GUARD_FIELD_ON		0x95
#define EEPROM_PCD_AWC_DRC_LUT_SIZE		0x97
#define EEPROM_PCD_AWC_DRC_LUT			0x98
#define EEPROM_Misc_Config			0xE8
#define EEPROM_DigiDelay_A_848_RW		0xE9
#define EEPROM_DigiDelay_B_848_RW		0xEA
#define EEPROM_DigiDelay_F_424_RW		0xEB
#define EEPROM_DigiDelay_15693_RW_FastHigh	0xEC
#define EEPROM_DigiDelay_18000_2_848		0xED
#define EEPROM_DigiDelay_18000_4_848		0xEE
#define EEPROM_TestbusMode			0xF0
#define EEPROM_TbSelect				0xF1
#define EEPROM_MapTb1_to_Tb0			0xF2
#define EEPROM_NumPadSignalMaps			0xF3
#define EEPROM_PadSignalMap			0xF4
#define EEPROM_TbDac1				0xF5
#define EEPROM_TbDac2				0xF6

#endif // PN3180_DEFS_H
