#ifndef IRQ_H
#define IRQ_H

#define NVIC_PRIORITY_GROUPING		3	// 4+0 bits

#define NVIC_PRIORITY_MATRIX		1
#define NVIC_PRIORITY_SYSTICK		2
#define NVIC_PRIORITY_MATRIX_CALC	3
#define NVIC_PRIORITY_USB		4
#define NVIC_PRIORITY_RENDERING		5
#define NVIC_PRIORITY_I2C_DMA		6
#define NVIC_PRIORITY_I2C		7
#define NVIC_PRIORITY_BUTTON		8

#endif // IRQ_H
